2024-01-31 10:35:30,897 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-31 10:35:30,899 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-31 10:35:30,900 MainThread udi_interface      INFO     __init__:<module>: User=None
2024-01-31 10:35:30,900 MainThread udi_interface      INFO     __init__:<module>: Home=C:\Users\chris
2024-01-31 10:35:30,900 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=C:\Users\chris\OneDrive\Documents\GitHub\udi-netatmo
2024-01-31 10:35:30,900 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=Not set
2024-01-31 10:35:30,900 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-31 10:35:30,914 MainThread udi_interface      ERROR    __init__:<module>: UDI interface initializaton failure: Traceback (most recent call last):
  File "C:\Users\chris\OneDrive\Documents\GitHub\udi-netatmo\udi_interface\__init__.py", line 21, in <module>
    from .interface import Interface
  File "C:\Users\chris\OneDrive\Documents\GitHub\udi-netatmo\udi_interface\interface.py", line 8, in <module>
    import markdown2
ModuleNotFoundError: No module named 'markdown2'

